### ISSUE TITLE
Why you need nvidia docker runtime inside singularity container?

### ISSUE THREAD

**Issue by al3x609** [tyson-swetnam/turbovnc-singularity#1]
According to the singularity manual the use of GPU is transparent within singularity. and you do not need to install drivers.

**Comment by tyson-swetnam** [comment]
It probably doesn't need the container-runtime at all - I threw it in the Singularity file after reading (more like skimming) this https://devblogs.nvidia.com/gpu-containers-runtime/

I was trying (and failing) to get the container to run on our HPC which requires you to module load CUDA to get the NVIDIA drivers. My presumption was that I could install the drivers and runtime in my container and avoid using their drivers.

I'm still waiting for the HPC center to get their versions of VirtualGL and NVIDIA properly configured. 

Any help on that front (singularity container for `vgrlrun`) would be much appreciated.

**Comment by al3x609** [comment]
**Maybe you already use these options, but I give my point of view.**
1.  singularity run  with the flag --nv (experimental), this load /dev /tmp  and opengl library
2.  load driver on runtime [singularity GPU](http://gpucomputing.shef.ac.uk/education/creating_gpu_singularity/)
3.  recipe container from bootstrap docker image  with GL generic implementation
  `BootStrap docker`
    `From nvidia/opengl:1.0-glvnd-runtime-centos7`
  or direct work over cuda + opengl image, example:
    `From nvidia/opengl:9.2-devel-ubuntu16.04`

  
Here you do not need drivers, except if your container runs a Distro that requires different drivers compared to the container implementation. And maybe this can create containers that are not very portable.
[dockerHub nvidia official repo proyect glvnd ](https://hub.docker.com/r/nvidia/opengl/)

 _When your bootstrap from docker image like [Nvidia Cuda](https://hub.docker.com/r/nvidia/cuda/), really work over project [libglvnd](https://github.com/NVIDIA/libglvnd)_

____

Reading your Singularity recipe:

- the latest version of virtualGL does not require separately installing libjpeg-turbo; because this version is compiled so it already contains it. unless you compile virtualGL from source code.
- Try proxy with Nginx, for high throughput on HPC cluster, Nginx will be work with buffer compression and send over rfb/web-socket more quickly.    
- for more performance, run vncserver with --noxstartup -nohttpd 
- I recommend an isolated use of **Openbox** like WM over **xfce4**, because it is lighter (and you no need install entere desktop environment), or **metacity**.

_i ' m sorry for my poor english_

**Comment by tyson-swetnam** [comment]
Thanks! I'm going to try these suggestions, will let you know how it goes.

and, your English is great!

**Comment by al3x609** [comment]
I made this. for a test 
no drivers, no opengl base image, no runtime, 

the files in my recipe are for control zombie process, setup novnc etc... but like a example, i show you the principal file and screenshot 

[gist](https://gist.github.com/al3x609/0e921b5891ed8f9e52bc3959a35dfcfb)

I run with (and outside of the container I have a Turbovnc server running on localhost:5901 port, but I need to run it inside the container, and install nginx too.) I need to polish some things but well ... this works
```
singularity build test.simg Singularity
singularity shell --nv test.simg
export DISPLAY=:1
vglrun paraview
```

**Comment by tyson-swetnam** [comment]
I'm building this now, will try and deploy it on our HPC. The sys admins are looking to use paraview with the GPUs, so this could be very helpful to them! Thanks again.

**Comment by al3x609** [comment]
maybe you can help me, How to build a container from a local simg, without install a singularity register?

example, I try:

```
Bootstrap: shub
From /images/image.simg
...
```
but it fail.

From manual, I'm not clear how to do this..
[path to a existing container on your local machine ](https://www.sylabs.io/guides/2.6/user-guide/build_a_container.html)

**Comment by tyson-swetnam** [comment]
http://singularity.lbl.gov/build-localimage

I think you're missing the `:` in `From:`

Bootstrap: localimage
From: /path/to/container/file/or/directory

**Comment by al3x609** [comment]
![](https://i.pinimg.com/236x/87/3d/66/873d66c3de7957991576715a0d5cf66d--semi-colon-programming.jpg)

jaja, and I forget one `:` ... thanks.

**Comment by al3x609** [comment]
Hey I found the fix for full acceleration, the fail is on the package libnvidia-container-tools, (or a similar name according to the Linux distribution )in Centos, if you remove this, the (--nv) work fine without bootstrap from nvidia/opengl:9.2-devel-ubuntu16.04
